apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
        - name: finance-container
          image: frawatson/finance:latest
          ports:
            - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: finance
spec:
  type: NodePort
  selector:
    app: finance
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8091
